import os
import requests
from typing import Dict, Any
from backend.app.config import Config

LOCAL_EXPLANATIONS = {
    "removed_field_reference": (
        "The rename changed the contract but not every consumer. Each stale read returns undefined (JS) "
        "or raises AttributeError (Python), and failures surface far from the edit, in another service, "
        "API response, or component."
    ),
    "function_signature_change": (
        "Positional callers keep working syntactically but bind arguments to the wrong parameters. "
        "This is a silent behavior change: no exception, wrong results. Explicit keyword arguments make "
        "the new contract visible at each call-site."
    ),
    "api_contract_change": (
        "Frontend and backend deploy independently, so a removed JSON key breaks already-shipped clients first. "
        "The UI renders blank fields instead of crashing, which makes the regression easy to miss in review."
    ),
    "auth_missing": (
        "Routes without an auth dependency are public by default in most Python frameworks. An admin listing "
        "endpoint without a guard exposes every account to unauthenticated enumeration, representing the highest blast radius."
    ),
    "sensitive_exposure": (
        "Secrets in responses travel to browsers, caches, and logs. Even debug prints persist in log aggregators "
        "with long retention. The fix is to never serialize secrets and to redact them at the logging boundary."
    ),
    "null_access": (
        "Database lookups return null for deleted or mistyped ids. Dereferencing without a guard turns a recoverable "
        "404 into a 500 that pages on-call. A three-line guard converts it back into a clean client error."
    ),
    "risky_migration": (
        "Migrations run before (or without) the matching code deploy. Dropping a column that code still reads creates "
        "a window where every request fails. Expand-then-contract ordering removes that window entirely."
    ),
    "missing_test": (
        "Changed auth and profile paths have no automated check, so the rename and signature edits ship on manual "
        "confidence alone. A focused test on the new contract catches regressions that review misses."
    )
}

def local_explain(finding: Dict[str, Any]) -> str:
    rule_id = finding.get("rule_id", "")
    description = finding.get("description", "")
    evidence = finding.get("evidence", {}) or {}
    files = ", ".join(evidence.get("files", [])[:6]) or finding.get("file_path", "")
    
    lines_formatted = ""
    for l in (evidence.get("lines") or [])[:5]:
        lines_formatted += f"• {l.get('file')}:{l.get('line')}: {l.get('snippet')}\n"

    why = LOCAL_EXPLANATIONS.get(rule_id, "This finding groups repository-level consequences of the change so review happens before commit, not after an incident.")
    suggestion = evidence.get("suggestion") or "Review the evidence, apply the minimal fix, and re-run ReGit impact analysis to confirm the signal clears."
    symbol = finding.get("symbol") or rule_id

    evidence_block = f"Key evidence:\n{lines_formatted}\n" if lines_formatted else ""

    return (
        f"## What happened\n{description}\n\n"
        f"## Why it matters\n{why}\n\n"
        f"## Blast radius\nAffected: {files}\n"
        f"{evidence_block}"
        f"## Fix (suggested)\n{suggestion}\n\n"
        f"## Review checklist\n"
        f"- [ ] Confirm every file above is updated or intentionally excluded\n"
        f"- [ ] Re-run impact for `{symbol}` until references hit zero\n"
        f"- [ ] Add or update a test that pins the new contract\n\n"
        f"_Generated by ReGit's deterministic explainer (offline mode). Connect an AI provider key to upgrade to LLM prose (evidence stays identical)._"
    )

def explain_finding(finding: Dict[str, Any]) -> Dict[str, str]:
    api_key = Config.OPENAI_API_KEY
    if not api_key:
        return {
            "text": local_explain(finding),
            "provider": "regit-local"
        }

    try:
        evidence = finding.get("evidence", {}) or {}
        prompt = (
            f"You are ReGit's AI Safety Assistant. Explain the following safety finding detected in the codebase.\n\n"
            f"Rule: {finding.get('rule_id')}\n"
            f"Severity: {finding.get('severity')}\n"
            f"Title: {finding.get('title')}\n"
            f"Description: {finding.get('description')}\n"
            f"Target: {finding.get('symbol')} in {finding.get('file_path')}\n"
            f"Evidence: {evidence}\n\n"
            f"Produce a structured markdown response with:\n"
            f"## What happened\n## Why it matters\n## Blast radius\n## Fix (suggested)\n## Review checklist"
        )

        response = requests.post(
            f"{Config.AI_BASE_URL}/chat/completions",
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}"
            },
            json={
                "model": Config.AI_MODEL,
                "messages": [
                    {"role": "system", "content": "You are a concise, senior code safety engineer explaining change impact."},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.2,
                "max_tokens": 800
            },
            timeout=15
        )

        if response.status_code == 200:
            data = response.json()
            content = data["choices"][0]["message"]["content"]
            return {"text": content, "provider": f"openai/{Config.AI_MODEL}"}
        else:
            return {"text": local_explain(finding), "provider": "regit-local (fallback)"}
    except Exception:
        return {"text": local_explain(finding), "provider": "regit-local (fallback)"}
