export interface ExplainInput {
  ruleId: string;
  severity: string;
  title: string;
  description: string;
  filePath: string;
  symbol?: string | null;
  evidence: {
    files: string[];
    symbols: string[];
    lines?: Array<{ file: string; line: number; snippet: string }>;
    relationship?: string;
    suggestion?: string;
  };
}

function localExplain(input: ExplainInput): string {
  const files = input.evidence.files.slice(0, 6).join(", ") || input.filePath;
  const lines = (input.evidence.lines ?? [])
    .slice(0, 5)
    .map((l) => `• ${l.file}:${l.line}: ${l.snippet}`)
    .join("\n");
  const why: Record<string, string> = {
    removed_field_reference:
      "The rename changed the contract but not every consumer. Each stale read returns undefined (JS) or raises AttributeError (Python), and failures surface far from the edit, in another service, API response, or component.",
    function_signature_change:
      "Positional callers keep working syntactically but bind arguments to the wrong parameters. This is a silent behavior change: no exception, wrong results. Explicit keyword arguments make the new contract visible at each call-site.",
    api_contract_change:
      "Frontend and backend deploy independently, so a removed JSON key breaks already-shipped clients first. The UI renders blank fields instead of crashing, which makes the regression easy to miss in review.",
    auth_missing:
      "Routes without an auth dependency are public by default in most Python frameworks. An admin listing endpoint without a guard exposes every account to unauthenticated enumeration, representing the highest blast radius of this batch.",
    sensitive_exposure:
      "Secrets in responses travel to browsers, caches, and logs. Even debug prints persist in log aggregators with long retention. The fix is to never serialize secrets and to redact them at the logging boundary.",
    null_access:
      "Database lookups return null for deleted or mistyped ids. Dereferencing without a guard turns a recoverable 404 into a 500 that pages on-call. A three-line guard converts it back into a clean client error.",
    risky_migration:
      "Migrations run before (or without) the matching code deploy. Dropping a column that code still reads creates a window where every request fails. Expand-then-contract ordering removes that window entirely.",
    missing_test:
      "Changed auth and profile paths have no automated check, so the rename and signature edits ship on manual confidence alone. A focused test on the new contract catches regressions that review misses.",
  };
  const body = why[input.ruleId] ?? "This finding groups repository-level consequences of the change so review happens before commit, not after an incident.";
  return `## What happened\n${input.description}\n\n## Why it matters\n${body}\n\n## Blast radius\nAffected: ${files}\n${lines ? `\nKey evidence:\n${lines}` : ""}\n\n## Fix (suggested)\n${input.evidence.suggestion ?? "Review the evidence, apply the minimal fix, and re-run ReGit impact analysis to confirm the signal clears."}\n\n## Review checklist\n- [ ] Confirm every file above is updated or intentionally excluded\n- [ ] Re-run impact for \`${input.symbol ?? input.ruleId}\` until references hit zero\n- [ ] Add or update a test that pins the new contract\n\n_Generated by ReGit's deterministic explainer (offline mode). Connect an AI provider key to upgrade to LLM prose (evidence stays identical)._`;
}

export async function explainFinding(input: ExplainInput): Promise<{ text: string; provider: string }> {
  const apiKey = process.env.OPENAI_API_KEY || process.env.AI_API_KEY;
  const baseUrl = process.env.AI_BASE_URL || "https://api.openai.com/v1";
  const model = process.env.AI_MODEL || "gpt-4o-mini";

  if (!apiKey) {
    // Small artificial delay so UI shows the "thinking" state
    await new Promise((r) => setTimeout(r, 900));
    return { text: localExplain(input), provider: "regit-local" };
  }

  try {
    const res = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        temperature: 0.3,
        max_tokens: 700,
        messages: [
          {
            role: "system",
            content:
              "You are ReGit, a change-centric code safety assistant. Explain deterministic static-analysis evidence concisely. Never invent files or line numbers. Structure: What happened / Why it matters / Blast radius / Fix / Review checklist. Keep under 350 words.",
          },
          {
            role: "user",
            content: JSON.stringify({
              rule: input.ruleId,
              severity: input.severity,
              title: input.title,
              description: input.description,
              symbol: input.symbol,
              files: input.evidence.files,
              lines: (input.evidence.lines ?? []).slice(0, 8),
              suggestion: input.evidence.suggestion,
            }),
          },
        ],
      }),
    });
    if (!res.ok) throw new Error(`AI upstream ${res.status}`);
    const json = await res.json();
    const text: string | undefined = json?.choices?.[0]?.message?.content;
    if (!text) throw new Error("empty completion");
    return { text, provider: model };
  } catch {
    return { text: localExplain(input), provider: "regit-local-fallback" };
  }
}
